# Generated by Django 2.1.8 on 2019-08-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=250)),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('message', models.TextField()),
                ('date_du_rdv', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'En attente'), ('B', 'Accepté'), ('C', 'Refusé')], max_length=1)),
                ('dateajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Enseignant'), ('B', 'Elève')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rendez_vous_web.Utilisateur'),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rendez_vous_web.Utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='rendez_vous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rendez_vous_web.Rendez_vous'),
        ),
        migrations.AddField(
            model_name='message',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rendez_vous_web.Utilisateur'),
        ),
    ]
