# Generated by Django 2.1.8 on 2019-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], max_length=1),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('enseignant', 'Enseignant'), ('élève', 'Élève')], max_length=1),
        ),
    ]
