# Generated by Django 2.1.8 on 2019-08-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0002_auto_20190829_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('enseignant', 'Enseignant'), ('élève', 'Élève')], max_length=10),
        ),
    ]
