# Generated by Django 2.2.1 on 2019-09-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0004_auto_20190925_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepté', 'Accepté'), ('refusé', 'Refusé')], max_length=50),
        ),
    ]
