# Generated by Django 2.2.1 on 2019-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0007_auto_20190925_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='fichier',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
