# Generated by Django 2.2.1 on 2019-09-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0009_auto_20190927_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='fichier',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
