# Generated by Django 2.1.8 on 2019-10-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0010_auto_20190928_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('selection', models.BooleanField()),
                ('dateajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rendez_vous',
            name='date_du_rdv',
        ),
        migrations.RemoveField(
            model_name='rendez_vous',
            name='status',
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='confirmation_eleve',
            field=models.CharField(choices=[('ET', 'En attente'), ('C', 'Confirmé'), ('D', 'Décliné')], default='ET', max_length=50),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='confirmation_enseignant',
            field=models.CharField(choices=[('ET', 'En attente'), ('C', 'Confirmé'), ('D', 'Décliné')], default='ET', max_length=50),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='message_annulation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='signalement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='rendez_vous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rendez_vous_web.Rendez_vous'),
        ),
        migrations.AlterField(
            model_name='message',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rendez_vous_web.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('EN', 'Enseignant'), ('EL', 'Élève')], max_length=10),
        ),
        migrations.AddField(
            model_name='creneau',
            name='rendez_vous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendez_vous_web.Rendez_vous'),
        ),
    ]
