# Generated by Django 2.2.1 on 2019-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous_web', '0011_auto_20191007_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='confirmation_eleve',
            field=models.CharField(choices=[('EA', 'En attente'), ('C', 'Confirmé'), ('D', 'Décliné')], default='EA', max_length=50),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='confirmation_enseignant',
            field=models.CharField(choices=[('EA', 'En attente'), ('C', 'Confirmé'), ('D', 'Décliné')], default='EA', max_length=50),
        ),
    ]
